name: cd

on:
  push:
    branches: [main]
  
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      
      - name: Install dependencies
        run: go mod tidy
      
      - name: Build it
        run: ./scripts/buildprod.sh

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: notely-448923

      - name: gcloud builds submit
        run: gcloud builds submit --project notely-448923 --tag us-central1-docker.pkg.dev/notely-448923/notely-ar-repo/notely:latest .